#
#  MetaData - API Generator.
#  Copyright (C) 2022-2023  Bill Hails
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
import secrets

def generate_dotenv(architecture):
    """
    writes a `.env` file to the root of the specified `architecture` directory.
    """
    with open('architectures/' + architecture + '/.env', "w") as fh:
        fh.write('# generated by the application, you should make sure this file is ignored by git\n')
        fh.write('AUTH_PORT=3000\n')
        fh.write('API_PORT=4000\n')
        fh.write('MAX_COMPLEXITY=1000\n')
        fh.write(f'ACCESS_TOKEN_SECRET={secrets.token_hex(64)}\n')
        fh.write(f'REFRESH_TOKEN_SECRET={secrets.token_hex(64)}\n')
